### ISSUE TITLE
Possible to use "iiif-content=" instead of "manifest="? 

### ISSUE THREAD

**Issue by hadro** [2SC1815J/Open_IIIF_Manifest_Link_In_Favorite_Viewer#3]
Thank you for the great plugin, I have found it useful for a number of years!

I'd like to try using this plugin with the relatively new Clover IIIF viewer: https://samvera-labs.github.io/clover-iiif/

But the URL construction uses "iiif-content=" instead of "manifest=" -- for example, see here: 
https://samvera-labs.github.io/clover-iiif/?iiif-content=https://iiif.io/api/cookbook/recipe/0003-mvm-video/manifest.json

Is it possible to configure this plugin to allow for that pattern?
Apologies if this is already in the documentation and I didn't understand correctly!

**Comment by 2SC1815J** [comment]
Thank you for your interest over the years!

If you use this plugin to open with the Clover IIIF viewer,  you can configure the following in the plugin [options](https://github.com/2SC1815J/open-in-iiif-viewer#options).
```
https://samvera-labs.github.io/clover-iiif/?iiif-content={manifest_URI}
```
Or simply,
```
https://samvera-labs.github.io/clover-iiif/?iiif-content=
```

If it doesn't work, please feel free to let me know again!

**Comment by hadro** [comment]
Aha, that worked perfectly! I thought I had tried that parameter before, but I guess I must have made a mistake.
Many thanks for your quick response.
